### ISSUE TITLE
Draft notes for `.mat` files from `ephys` folder

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/fee-lab-to-nwb#22]
**pipeline**_ `session_id` _ `session_date` _LH_NCM_g0.mat
- has all other .mat files content, including the auditory data

**syncData_** `session_date`.mat:
-  'Audio_eventTimes' is the timestamps for the auditory, however there is a mismatch between the length of the .wav file and the length of timestamps: 5222.57295 vs len(audio_timestamps) is 10447
- 'IMEC_eventTimes' is the timestamps for SpikeGLX
- 'b' is a shape of (2, 1): [[ 9.99991717e-01], [-9.00426576e-04]]
- 'sp' is an ndarray of (1, 1): [[(array(['/om2/user/mhapp/temp_wh.dat'], dtype='<U27'), array([[383]], dtype=uint16), array(['int16'], dtype='<U5'), array([[0]], dtype=uint8), array([[30000]], dtype=uint16), array([[1]], dtype=uint8), array([[2.03288246e-03],,         [2.29954692e-03],, ...

**timingData**_ `session_date`.mat:
- 'motifTimingData' is the timestamps of motifs (repeating patterns in .wav file) shape of (3362, 2) motif_id, timestamp

**wfData**_ `session_date`.mat
- 'best_wfs' best waveforms array shape of (128, 82)

**Comment by CodyCBakerPhD** [comment]
Only thing left is waveforms and that one sync problem I'm helping with. Waveforms are also probably optional as well.
