### ISSUE TITLE
[ToDo]: add behavior interface for ophys

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/fee-lab-to-nwb#3]
- [ ] SpatialSeries from the .csv
- [ ] `external_file` mode MovieDataInterface

**Comment by weiglszonja** [comment]
Based on the email thread: 

> home_pos-speed-in_[timestamp].csv timestamps for frames in behavior video as system time recorded by bonsai. following the timestamp is additional tracking data, which can be ignored

Based on this they only want to store the timestamps and omit the tracking data, but I will double-check with them.

**Comment by CodyCBakerPhD** [comment]
Hmm.. OK, so they just want the TIFF stacks with the behavioral video (whose timestamps come from the .csv). Are they *sure* they don't want to include extrapolated position of subject over time? It's super easy to do, lol.
