### ISSUE TITLE
Run conversions from fresh environment

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/fee-lab-to-nwb#50]
Testing the ephys, ophys conversions starting off from a fresh environment and following the guide in README.md to make sure everything works as expected. Also to fix any issues that come up with a fresh install.

`Python` 3.10
`neuroconv` 0.2.1
`pynwb` 2.2.0
`spikeinterface` 0.96.1
`spikeextractors` 0.9.10
`roiextractors` 0.5.1

**Comment by CodyCBakerPhD** [comment]
Is this working well now?

**Comment by weiglszonja** [comment]
Not yet, now I also have:
```
Failed validating 'additionalProperties' in schema['properties']['Ophys']['properties']['ImagingPlane']['items']:
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('excitation_lambda', 'imaging_rate' were unexpected)
```

**Comment by weiglszonja** [comment]
Yes, thats it! Thank you for keeping an eye on this! 👍

**Comment by CodyCBakerPhD** [comment]
Done, try with NeuroConv==0.2.2 and then we should be good to close

**Comment by weiglszonja** [comment]
Okay, `NeuroConv==0.2.2` works for the stub test conversions :)

**Comment by weiglszonja** [comment]
Will close this issue from a PR.
